# version: "3"

# services:
#   mlops-airflow:
#     image: mlopsassignment2:latest
#     volumes:
#       - ./airflow:/opt/airflow
#     ports:
#       - "8080:8080"
#     command: airflow standalone

version: "3"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-data:/var/lib/postgresql/data

  airflow-init:
    image: mlopsassignment2:latest
    command: ["airflow", "db", "init"]
    depends_on:
      - postgres

  mlops-airflow:
    image: mlopsassignment2:latest
    volumes:
      - ./airflow:/opt/airflow
    ports:
      - "8080:8080"
    command: airflow standalone
    depends_on:
      - airflow-init

volumes:
  postgres-data:
